services:
  api_host: 'nomad-test.support.ikz-berlin.de'
  api_base_path: '/nomad-oasis'
  upload_limit: 1000  # enough descriptors available ?
  # upload_members_group_search_enabled: true  # true is now the default

oasis:
  is_oasis: true
  uses_central_user_management: false

plugins:
  entry_points:
    options:
      nomad_north_jupyter.north_tools:jupyter:
        north_tool:
          image: ghcr.io/fairmat-nfdi/nomad-north-jupyter:latest
    # exclude:
    #   - apps/3_experiment/2_eels  # eels db has been removed from NOMAD for license reasons
    #   - nomad_measurements.transmission:parser_entry_point  # temporarily deactivated anyway

meta:
  deployment: 'oasis'
  deployment_url: 'nomad-test.support.ikz-berlin.de/nomad-oasis/api'  # why test?
  maintainer_email: 'edv@ikz-berlin.de'

north:
  enabled: false
# north: temporarily deactivated north, after the committing of https://github.com/IKZ-Berlin/nomad-oasis-ikz/blob/a7d3ea86f916a1a13e9847a7ed26140595f95693/configs/nomad.yamlin all north containers and its underlying infrastructure have been refactored, we should rather build on the new containers rather than sticking to old copies of containers with almost the same functionality

logstash:
  enabled: false

temporal:
  enabled: true

mongo:
  db_name: nomad_oasis_v1

elastic:
  entries_index: nomad_oasis_entries_v1
  materials_index: nomad_oasis_materials_v1

# logtransfer:
#     enabled: true
#     transfer_interval: 10

# recover the customized ui from, that ui should rather go to the nomad-ikz-plugin instead of hardcoding it here in the config file https://github.com/IKZ-Berlin/nomad-oasis-ikz/blob/a7d3ea86f916a1a13e9847a7ed26140595f95693/configs/nomad.yaml